### ISSUE TITLE
Best wishes for the development work here!

### ISSUE THREAD

**Issue by altbdoor** [helma-dev/kusaba-helma#4]
Not exactly an issue, but I want to wish the best for you and your work here.

At some point in my life, I got too busy with things, and I've stopped working on Helma completely. Only realized about how Helma is doing now from your recent star on my old repo.

Glad to see that someone will take care of Helma. Godspeed, and good luck ❤️

**Comment by helma-dev** [comment]
Thank you for your kindness! Helma was one of my favorite websites, and I was crushed to see it shut down and that motivated me to do something about it. 
Still, as someone who's a complete newbie to this, that repo with the old code that I could use and even expand on was a godsend. I am really thankful for your work.

**Comment by altbdoor** [comment]
@helma-dev hello sir. I have some news on old Helma. Could you please contact me on my email? You should find it in my GitHub profile.

Edit: sorry for the panic. I was just contacted by a close friend of HelmaAdmin, and hence, just got to know on what happened to him... I suppose the community is well informed about this by now.
